# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name:("myjavaproject,freefire,autoheadshotmod")

on:("function aimAtHead{target)
getheadcordinates{head}
  push:git push origin main
    branches: [ "feature_autoheadshot_bug_aim_issue" ]
  pull_request:[ "autoheadshot_feature" ]
    branches: [ "autoheadshotfreefire_120fpsgameplay" ]

jobs:"autoheadshot_task"
  build:"webpack --mode-production"

    runs-on: ("unity")

    steps:("java")
    - uses: ("autoheadshot_adjustments_120fpsfreefiregameplay')
    - name: ("autoheadshot")
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
